packages:
  - 'packages/*'

catalog:
  react: ^19.2.0
  react-dom: ^19.2.0
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.1
  typescript: ^5.9.3
  vite: ^7.1.9
  vite-plugin-dts: ^4.5.4
  vitest: ^3.2.4
  '@vitejs/plugin-react': ^5.0.4
  eslint: ^9.37.0
  '@typescript-eslint/eslint-plugin': ^8.46.0
  '@typescript-eslint/parser': ^8.46.0
  eslint-plugin-react-hooks: ^7.0.0
  eslint-plugin-react-refresh: ^0.4.20


